# Generated by Django 3.0 on 2019-12-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
